; PlatformIO Project Configuration File
;
; Build options: build flags, build src filter
; Upload options: custom upload port, speed, extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
; USART0_init_9600 — must match monitor_speed
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600